# package|repository|tag|meson options
mutter|https://github.com/GNOME/mutter.git|48.8|-Dx11=true -Dwayland=false -Dxwayland=false -Dtests=disabled -Dprofiler=false
gnome-session|https://github.com/GNOME/gnome-session.git|48.0|-Dx11=true
gdm|https://github.com/GNOME/gdm.git|48.0|-Dx11-support=true -Dgdm-xsession=true -Dwayland-support=false
gnome-shell|https://github.com/GNOME/gnome-shell.git|48.8|-Dtests=false
