overwrite: true
keepDistributor: true
kernel_params: [ "quiet", "splash", "rw", "nvidia-drm.modeset=1", "pcie_aspm=off", "zswap.enabled=1", "zswap.compressor=zstd", "zswap.max_pool_percent=20" ]
defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "saved"
    GRUB_DISABLE_SUBMENU: true
    GRUB_TERMINAL_OUTPUT: "gfxterm"
    GRUB_GFXMODE: "1920x1080,640x480,auto"
    GRUB_GFXPAYLOAD_LINUX: "keep"
    GRUB_BACKGROUND: "/boot/grub/splash.png"
    GRUB_DISABLE_RECOVERY: true
    GRUB_DISABLE_OS_PROBER: true
    GRUB_CMDLINE_LINUX_DEFAULT: "quiet splash nvidia-drm.modeset=1 pcie_aspm=off zswap.enabled=1 zswap.compressor=zstd zswap.max_pool_percent=20"
