region:                     ""
zone:                       ""

adjustLiveTimezone:   true
useSystemTimezone:    true

localeGenPath:             "/etc/locale.gen"

geoip:
    style:    "json"
    url:      "https://geoip.kde.org/v1/calamares"
    selector: "timezone"  # auto-detect timezone