---

dontChroot: true
timeout: 300
i18n:
    name: "Restoring preserved user files and data"

script:
    - command: "-python3 /usr/local/lib/horizon-installer/restore_data.py \"${ROOT}\""
      timeout: 300

